// OTRise content — ported verbatim from asuthar1103/otrise index.html (LEVELS array).
// Rule: every question stores its correct answer first in opts, with a:0. Shuffled at render time.
window.OTRISE_PASS = 6;
window.OTRISE_LEVELS = [
{ title:"First Day at the Plant", role:"Level 1 · Rookie", diff:1, badge:"OT Aware",
  desc:"The absolute basics: what OT actually is and why it isn't just 'IT with hard hats'.",
  questions:[
    { q:"What does 'OT' stand for in industrial cybersecurity?", opts:["Operational Technology","Online Terminal","Output Transmission","Organizational Testing"], a:0, why:"OT — Operational Technology — is the hardware and software that monitors and controls physical processes: pumps, valves, motors, production lines." },
    { q:"Which of these is a typical OT device?", opts:["A PLC controlling a pump","An office printer","A payroll server","A conference room webcam"], a:0, why:"A PLC (Programmable Logic Controller) is a rugged industrial computer that directly controls machinery. The others are classic IT equipment." },
    { q:"What does an HMI let a plant operator do?", opts:["View and control the process from a screen","Send marketing emails","Design mechanical parts","Manage employee records"], a:0, why:"The Human-Machine Interface is the operator's window into the process — live values, alarms, and controls for the plant." },
    { q:"SCADA stands for…", opts:["Supervisory Control And Data Acquisition","Secure Central Access Data Application","System Check And Device Alert","Standard Control And Diagnostic Array"], a:0, why:"SCADA systems supervise and collect data from processes spread over large areas — pipelines, power grids, water networks." },
    { q:"In a typical office IT system, confidentiality comes first. What comes first in OT?", opts:["Safety and keeping the process running","Confidentiality, same as IT","Fast internet speed","Data storage capacity"], a:0, why:"In OT the priority flips: a leaked file is bad, but a compromised controller can stop production or physically hurt people. Safety and availability lead." },
    { q:"Why can't OT systems simply install every update immediately like office laptops?", opts:["Updates can force downtime and must be tested against the process first","OT systems never need updates","Updates are illegal in factories","OT devices have unlimited storage for patches"], a:0, why:"Many plants run 24/7, and an untested patch can break control software. Patching in OT is planned around shutdown windows and vendor validation." },
    { q:"A colleague says: \"Our plant network is air-gapped, so hackers can't reach it.\" What's the realistic view?", opts:["True air gaps are rare — vendor links, USBs and remote access usually create paths in","He's right, air gaps make plants unhackable","Air gaps only fail during storms","Hackers can only attack websites, not plants"], a:0, why:"Modern plants exchange data with business systems, vendors and remote engineers. Even 'isolated' networks are reachable via USB media and temporary connections — Stuxnet proved it." },
    { q:"Why do attackers bother targeting industrial systems at all?", opts:["Disruption, extortion and sabotage of physical operations can be very valuable","Only to test their internet speed","OT systems store cat videos","They can't — OT has no value to attackers"], a:0, why:"Stopping a pipeline, factory or power grid creates enormous pressure — for ransom, politics or sabotage. Physical impact is exactly what makes OT a target." }
  ]},
{ title:"Threats on the Floor", role:"Level 2 · Operator", diff:2, badge:"Threat Spotter",
  desc:"Everyday attack paths: USB sticks, phishing, remote access and bad habits.",
  questions:[
    { q:"You find a USB stick in the plant parking lot. What do you do?", opts:["Hand it to security/IT — never plug it into any plant machine","Plug it into the HMI to find the owner","Plug it into your work laptop 'just quickly'","Format it and keep it"], a:0, why:"Dropped USB sticks are a classic attack. Stuxnet entered its target via removable media. Unknown media never touches OT equipment." },
    { q:"Which email is most likely phishing?", opts:["\"Urgent: your SCADA password expires in 1 hour — click here to keep access\"","A newsletter you subscribed to","A meeting invite from your known manager","A delivery note you were expecting from a known supplier"], a:0, why:"Urgency + credential link = phishing pattern. Attackers often steal IT credentials first, then pivot toward OT systems." },
    { q:"Why are default passwords (admin/admin) on OT devices so dangerous?", opts:["They're published in manuals online — attackers try them first","They use too much memory","They slow the network down","They expire too quickly"], a:0, why:"Default credentials for PLCs, HMIs and routers are freely documented. Scanning tools try them automatically — changing them is step one of hardening." },
    { q:"A vendor asks for permanent, always-on remote access to 'their' machine in your plant. Best practice?", opts:["Time-limited access via a controlled gateway with MFA, monitored and approved per session","Give them a permanent VPN with full network access","Share the operator's own password","Let them install their own 4G modem on the PLC"], a:0, why:"Remote access is one of the top OT attack vectors. It should be brokered, time-boxed, least-privilege and logged — never a standing open door." },
    { q:"Ransomware hits the office (IT) network. Why can production still end up stopping?", opts:["Shared services and connections mean plants often halt as a precaution or dependency","Ransomware improves plant performance","It can't — IT and OT are always separate","Only printers are affected by ransomware"], a:0, why:"Colonial Pipeline 2021: the ransomware hit IT, but operations were shut down because of dependencies and uncertainty. IT incidents become OT incidents fast." },
    { q:"Why is an accurate asset inventory considered the first step of any OT security program?", opts:["You can't protect, patch or monitor devices you don't know exist","Inventories are only needed for accounting","It makes the network faster","Auditors like long spreadsheets"], a:0, why:"Unknown PLCs, forgotten modems and undocumented links are where attackers live. Visibility comes before any control." },
    { q:"During maintenance you notice an unlabelled cellular modem wired to a controller. What is this?", opts:["A possible rogue/shadow connection that bypasses all network defenses — report it","Normal — more connectivity is always good","A Wi-Fi booster for the break room","Something to ignore if the machine still runs"], a:0, why:"Undocumented modems create a direct path from the internet to the process, skipping every firewall. They must be verified, authorized or removed." },
    { q:"A contractor wants to connect his personal laptop directly to the control network 'to save time'. You should…", opts:["Refuse — only approved, scanned, managed devices connect to OT","Allow it if he promises he has antivirus","Allow it outside office hours only","Allow it if the laptop looks new"], a:0, why:"Transient devices are a major infection path into OT. Plants use dedicated, hardened engineering machines and controlled file-transfer processes instead." }
  ]},
{ title:"Blueprints & Barriers", role:"Level 3 · Engineer", diff:3, badge:"Architect",
  desc:"Network architecture: the Purdue model, zones, conduits, DMZs and segmentation.",
  questions:[
    { q:"In the Purdue reference model, what lives at Level 0?", opts:["Sensors and actuators touching the physical process","The corporate email server","The ERP system","Cloud analytics dashboards"], a:0, why:"Level 0 is the physical layer — instruments and final elements (valves, motors). Levels rise through control (1), supervision (2), operations (3) to enterprise (4/5)." },
    { q:"What is the main purpose of the industrial DMZ (the 'Level 3.5' between IT and OT)?", opts:["Broker all data exchange so no direct connection exists between enterprise and control networks","Host the company website","Store operator lunch menus","Make the network diagram look bigger"], a:0, why:"The iDMZ terminates connections from both sides — historians, patch servers, jump hosts — so enterprise systems never talk straight to controllers." },
    { q:"Why is a 'flat' network (everything on one segment) dangerous in a plant?", opts:["One compromised device can reach every controller directly","Cables lie flat on the floor","It uses too many IP addresses","Flat networks are slower by definition"], a:0, why:"Without segmentation there is nothing to stop lateral movement: infect one laptop, reach every PLC. Segmentation contains the blast radius." },
    { q:"In IEC 62443 language, what are 'zones' and 'conduits'?", opts:["Groups of assets with shared security needs, and the controlled channels between them","Physical fences and corridors in the plant","Types of firewall hardware","Wi-Fi frequency bands"], a:0, why:"A zone groups assets with similar criticality; conduits are the defined, restricted communication paths between zones — each with its own security requirements." },
    { q:"The enterprise wants live production data. The secure pattern is…", opts:["OT pushes data outward to a historian/broker in the DMZ; enterprise reads from there","Give every office PC direct read access to the PLCs","Email CSV files from the HMI every hour","Put the PLC on the internet with a strong password"], a:0, why:"Data flows outward through an intermediary; nothing from the enterprise side initiates connections into the control network." },
    { q:"What is a data diode (unidirectional gateway) used for?", opts:["Physically guaranteeing data flows in one direction only, e.g. out of a critical network","Boosting Wi-Fi signal","Encrypting USB sticks","Cooling the server room"], a:0, why:"Hardware-enforced one-way flow lets you export monitoring data from critical zones (like safety systems) with no physical possibility of traffic coming back in." },
    { q:"Which firewall rule is the most suspicious on an IT→OT boundary?", opts:["'Any' source allowed to reach the PLC subnet on all ports","DMZ historian allowed to receive data from Level 3","Jump host reachable from a named admin subnet with MFA","Time-sync (NTP) from a defined internal server"], a:0, why:"'Any/any' rules to controller networks defeat the entire purpose of the boundary. Rules should be specific: named sources, named destinations, named ports." },
    { q:"Where should a vendor's remote engineering session terminate?", opts:["On a monitored jump host in the DMZ, which then connects onward under control","Directly on the safety controller","On the operator's personal phone","On any machine that's free"], a:0, why:"The jump host pattern gives one controlled, recorded, policy-enforced entry point — instead of tunnels landing anywhere in the control network." }
  ]},
{ title:"Speaking Machine", role:"Level 4 · Specialist", diff:4, badge:"Protocol Pro",
  desc:"Industrial protocols and the attack surface: Modbus, DNP3, OPC UA, engineering workstations.",
  questions:[
    { q:"What is the core security weakness of classic Modbus TCP?", opts:["No authentication — any device that can reach the port can read and write","It only works on Fridays","It encrypts too strongly to monitor","It requires cloud connectivity"], a:0, why:"Modbus was designed decades before security mattered. If you can reach a Modbus device, you can typically write coils and registers — the network must provide the protection the protocol lacks." },
    { q:"An attacker on the control network sends valid 'write' commands to a PLC using the normal protocol. Why is this hard to detect?", opts:["The traffic looks like legitimate commands — nothing is 'malformed'","PLCs automatically block all attackers","Writes are always encrypted","Firewalls read the attacker's mind"], a:0, why:"Living-off-the-land in OT: abuse of legitimate protocol functions. Detection needs context — who sends, from where, when, and does the command make process sense." },
    { q:"What does OPC UA offer that classic OPC (DCOM-based) did not?", opts:["Built-in authentication, encryption and signing","Faster floppy disk support","Guaranteed air-gapping","Free hardware upgrades"], a:0, why:"OPC UA was designed with security in the protocol: certificates, encrypted sessions, user authentication. Classic OPC relied on notoriously fragile DCOM settings." },
    { q:"Why is the engineering workstation (EWS) such a prized target?", opts:["It holds the tools and project files to legitimately reprogram controllers","It has the best graphics card","Operators store music on it","It is always offline"], a:0, why:"Own the EWS and you own the process logic: attackers download modified programs to PLCs with the vendor's own software — exactly how Stuxnet and Triton worked." },
    { q:"DNP3 is widely used in power and water utilities. What does 'DNP3 Secure Authentication' add?", opts:["Verification that critical commands come from an authorized source","Color graphics on RTUs","Automatic ransom payments","Unlimited bandwidth"], a:0, why:"SAv5 adds challenge-response authentication for critical operations, addressing plain DNP3's total trust in whoever is on the wire." },
    { q:"Why can an ordinary IT vulnerability scan be dangerous on a live control network?", opts:["Fragile embedded devices can hang or reboot when probed — stopping the process","Scans are boring","It voids the office coffee machine warranty","Scanning always requires internet"], a:0, why:"Legacy PLC/RTU network stacks were never built for unexpected packets. OT asset discovery prefers passive monitoring, with active queries used carefully in maintenance windows." },
    { q:"How could an attacker change a controller's behavior without touching its logic program?", opts:["Replace or tamper with the device firmware","Repaint the cabinet","Rename the HMI shortcuts","Update the plant's wall clock"], a:0, why:"Firmware attacks sit below the application logic and survive logic re-downloads. Integrity verification and controlled update processes are the defense." },
    { q:"Which detection approach fits OT networks best as a baseline?", opts:["Passive monitoring that learns normal traffic and flags new connections or commands","Weekly aggressive port scans of all PLCs","Installing antivirus directly on every 20-year-old controller","Blocking all traffic and hoping"], a:0, why:"OT traffic is highly repetitive, which makes anomaly detection powerful: a new master, a first-ever write, a config download at 3 AM all stand out — without touching fragile endpoints." }
  ]},
{ title:"Standards & Risk", role:"Level 5 · Professional", diff:5, badge:"Risk Professional",
  desc:"IEC 62443, IEC 61511, safety systems, and how professionals actually reason about cyber-physical risk.",
  questions:[
    { q:"What is IEC 62443?", opts:["The international standard series for industrial automation and control system security","A Wi-Fi certification","A forklift driving license","An accounting regulation"], a:0, why:"IEC 62443 covers programs, processes, system requirements and component requirements for securing industrial automation — the reference framework for OT security." },
    { q:"IEC 62443 defines Security Levels SL1–SL4. What does SL4 protect against?", opts:["Sophisticated attackers with extensive resources and motivation (state-level)","Rain damage","Accidental coffee spills only","Slow internet connections"], a:0, why:"The SLs scale with attacker capability: SL1 casual/accidental, SL2 simple intentional, SL3 sophisticated, SL4 sophisticated with extensive resources. Target SLs are chosen per zone based on risk." },
    { q:"What is a Safety Instrumented System (SIS)?", opts:["An independent layer that automatically forces the process to a safe state when limits are breached","The plant's CCTV system","A backup email server","Software for HR safety training"], a:0, why:"The SIS is the last automated line of defense — independent sensors, logic solver and final elements that trip the process before an unsafe condition becomes an accident." },
    { q:"A SIS is certified SIL 3. Does that mean it is resistant to cyber attack?", opts:["No — SIL measures reliability against random/accidental failures, not against intelligent attackers","Yes, SIL 3 includes hackers","Yes, if the cabinet is locked","SIL only applies to elevators"], a:0, why:"IEC 61511's SIL targets assume accidental failure modes. A deliberate attacker who reprograms the logic solver defeats the certification's assumptions — which is why 61511 now requires a security risk assessment for the SIS." },
    { q:"Why do many OT practitioners argue the IT 'CIA triad' fits OT poorly, proposing instead to assess Controllability, Observability and Operability (COO)?", opts:["Because what matters is whether operators can still control, see, and run the process — not primarily data secrecy","Because confidentiality is illegal in factories","Because OT has no data at all","Because triads must always be renamed"], a:0, why:"In the cyber-physical risk knowledge base, the risk-bearing object is the physical process: an attack matters when you lose the ability to control it, observe its true state, or keep operating. CIA describes information, COO describes the process. (CIA still applies to e.g. recipes and credentials.)" },
    { q:"Mature OT security design assumes the perimeter will eventually fail. What is the key 'second layer' question to ask?", opts:["\"If an attacker is already inside, is the process still controllable, observable and bounded?\"","\"Who do we blame first?\"","\"Can we buy a second firewall of the same brand?\"","\"Should we turn off all alarms to reduce noise?\""], a:0, why:"Prevention (layer 1) will someday fail. Resilient design preserves operational integrity under degraded trust — bounded authority, sanity-checked commands, independent protection — so compromise doesn't instantly become catastrophe." },
    { q:"There are few good statistics on OT attacks. How do professionals still quantify cyber-physical risk defensibly?", opts:["Estimate the probability their own defenses fail if attacked (PFA), and let consequence severity drive priority","Wait a few decades for enough incidents","Copy last year's IT risk register","Use gut feeling and a red/yellow/green sheet only"], a:0, why:"The cyber-physical risk approach: you can't derive frequencies from scarce attack data, but you can analyze your own barriers — the conditional probability that defenses fail given an attack — and weigh scenarios by the physical consequence ('risk pressure'), aligning with existing safety-risk criteria." },
    { q:"Where does NIST SP 800-82 fit in?", opts:["It's the (US) NIST guide to OT security — practical guidance complementing IEC 62443","It's a firewall product","It's an EU privacy law","It replaces the need for engineering"], a:0, why:"SP 800-82 ('Guide to Operational Technology Security') gives architecture, risk and control guidance for OT, widely used alongside IEC 62443 and sector regulations." }
  ]},
{ title:"Incident Command", role:"Level 6 · Expert", diff:6, badge:"OT Cyber Expert",
  desc:"Real attacks and expert judgment: Stuxnet, Triton, Ukraine — and the calls you'd have to make.",
  questions:[
    { q:"What made Stuxnet (discovered 2010) a landmark in OT security?", opts:["It crossed an air gap and made PLCs physically destroy equipment while operators saw normal readings","It was the first email virus","It only defaced websites","It attacked smartphones"], a:0, why:"Stuxnet spread via USB and vendor laptops, injected code into Siemens S7 PLCs, spun centrifuges out of tolerance and replayed normal data to the operators — proof that malware can cause targeted physical destruction while blinding the control room." },
    { q:"Why is Triton/TRISIS (2017, Saudi petrochemical plant) considered a red line even among ICS attacks?", opts:["It targeted the Safety Instrumented System itself — the layer that prevents explosions and loss of life","It stole cafeteria menus","It only affected printers","It was purely a phishing test"], a:0, why:"Triton reprogrammed Triconex safety controllers. Disabling the SIS while an attacker also holds the control system removes the last automated barrier between an upset and a catastrophe. The plant tripped safe — partly luck." },
    { q:"In the 2015 Ukraine power grid attack, how were the breakers actually opened?", opts:["Attackers used the operators' own SCADA sessions/tools after months of quiet preparation","A lightning strike","A software bug with no attacker","Solar flares"], a:0, why:"After spear-phishing and long reconnaissance, attackers took over operator workstations and clicked the breakers open themselves — then wiped systems and jammed the call center. Legitimate functionality, hostile hands." },
    { q:"What did Industroyer/CrashOverride (Ukraine, 2016) demonstrate that generic malware had not?", opts:["Malware speaking grid protocols (like IEC 60870-5-104/61850) natively to command substations directly","That antivirus stops all ICS attacks","That grids cannot be attacked twice","That only USB sticks matter"], a:0, why:"Industroyer contained protocol modules to issue breaker commands itself — no human at the HMI needed. Attack capability had been productized for the grid domain." },
    { q:"Scenario: Ransomware detonates in your company's IT network. OT is 'probably' clean. As OT lead, your soundest immediate posture is…", opts:["Pre-planned segmentation/isolation of OT, heightened monitoring, and keep operating only what you can verify as trustworthy","Do nothing — OT is someone else's problem","Immediately connect OT to IT to 'help' IT recover","Pay the ransom from petty cash"], a:0, why:"Colonial Pipeline's lesson: uncertainty about OT integrity is itself an operational risk. Prepared isolation playbooks, out-of-band monitoring and verified-trust operation beat both panic shutdown and blind continuation.", scenario:true },
    { q:"Scenario: During unexplained controller reboots, an engineer suggests bypassing the SIS 'to stop nuisance trips' while you investigate. Expert response?", opts:["Refuse — with possible compromise in play, weakening the independent protection layer is exactly the wrong move; investigate with the SIS armed","Agree — trips are annoying","Bypass it but only on night shift","Bypass it and also disable alarms for quiet"], a:0, why:"Triton logic: an attacker (or fault) plus a bypassed SIS equals no remaining barrier. Unexplained controller behavior is a potential safety-critical incident; the protection layer stays in, and any bypass must be visible, authorized and time-limited.", scenario:true },
    { q:"Scenario: A vendor states their new device 'complies with IEC 62443-4-2 and the CRA, so your risk is covered.' The professional reading is…", opts:["Compliance is an input, not proof — resilience depends on how the device is deployed, connected and operated in *your* installation","Compliance means nothing can ever go wrong","Certificates replace the need for architecture","Buy two, so you're doubly compliant"], a:0, why:"A certified product in a flat network with shared passwords is still a soft target. Product security must be translated through deployment context, automation function and operational consequence — installation-level risk is yours to assess.", scenario:true },
    { q:"Scenario: The board asks, 'Are we secure now?' after a big OT security investment. The most honest expert answer is…", opts:["\"We've reduced specific risks measurably; here's what an attacker would still have to defeat, what we'd detect, and how the process stays safe if they succeed\"","\"Yes, 100% secure, forever\"","\"No idea, but the auditors were happy\"","\"Security is done; we can disband the team\""], a:0, why:"Expert maturity is speaking in residual risk: which scenarios are now bounded, what detection and response cover, and how safety is preserved under compromise — not absolute promises no honest engineer can make.", scenario:true }
  ]}
];
